### ISSUE TITLE
Add more styling in the website

### ISSUE THREAD

**Issue by abhisheksharma010** [opencodeiiita/Collaborative-Web-2023#152]
In the website i want to enhance styling of fotter and add Parallx effect in the website

**Comment by TheDivineAurora** [comment]
claim

**Comment by abhisheksharma010** [comment]
This is not any point issue it is only proposal that i want to do in the project .

**Comment by GammaMicrowave** [comment]
I am assigning this task to you you would be rewarded 10 points for the same. Also try to make the navbar highlight the section which is currently visible on the screen.

**Comment by abhisheksharma010** [comment]
@GammaMicrowave ok i will do i will share you design what in my mind before moving forward

**Comment by GammaMicrowave** [comment]
also I want you to remove that 100vh height instead use min-height as some pages won't have default 100vh height and if they extend beyond it it would start overlapping with next page. Also another change in background that I wanna propose is alternate the gradient between each section so instead of abrupt changes in background it would blend in better.

**Comment by abhisheksharma010** [comment]
Yes i am also interested in changing the gradient colour i want to add the parallax effect in some sections. Changing from 100vh may cause background problems in the website i had tried min -height before this work on my own projects but this did not work for me

**Comment by saisreesatyassss** [comment]
claim

**Comment by GammaMicrowave** [comment]
@abhisheksharma010 pull the changes before working since I have made some minor changes.

**Comment by abhisheksharma010** [comment]
Okh
